### ISSUE TITLE
Convert all audio files to wav (lossless) format.

### ISSUE THREAD

**Issue by esklarski** [Atelier-Mycelia/Amanita#6]
Ensure compliance with audio content guidelines.

See 2.7:
[https://assetstore.unity.com/publishing/submission-guidelines#2. Product Content](https://assetstore.unity.com/publishing/submission-guidelines#2.%20Product%20Content)

**Comment by CG-Tespy** [comment]
The non-wav audio files I found outside the Sherlock folder:

* CKZ_-_09_-_Youre_Not_Real.mp3
  * Folder: The Facility
  * Copyright: Attribution-NonCommercial-ShareAlike 3.0 International: http://creativecommons.org/licenses/by-nc-sa/3.0/
  * Source: Dim Shred and Innuendo Album @ http://freemusicarchive.org/music/CKZ/Dim_Shrewd_and_Innuendo/09_ckz_-_you_are_not_real

* Music.mp3
  * Folder: TheHunter
  * Copyright: ???
  * Source: N/A

* PraxMusic.mp3
  * Folder: JumpingPrax
  * Copyright: Attribution-NonCommercial-ShareAlike: http://creativecommons.org/licenses/by-nc-sa/3.0/
  * Source: http://freemusicarchive.org/music/DOt/CC-10_Europe_Mixtape/IMF_1309

* VO1.mp3, VO2.mp3, VO3.mp3 (yes, three files)
  * Folder: SayHolds
  * Copyright: ???
  * Source: http://www.nextup.com

Most of the above info was copy-pasted from the files' metadata. I don't know which ones we'll be allowed to keep, but I'll convert all of them anyway

**Comment by esklarski** [comment]
Closed by #8
